### ISSUE TITLE
Utilizando git e GitHub

### ISSUE THREAD

**Issue by vaniaon** [solidarizesw/wiki#2]
Criar wiki sobre comandos básicos do git, issues e projetos no GitHub

**Comment by williamguilhermesouza** [comment]
- [x] Criar página com comandos básicos
- [x] Criar página sobre issues
- [x] Criar página sobre Projetos

**Comment by LuccasOliveira** [comment]
A apresentação foi concluída ontem e está sobre revisão dos colaboradores.

**Comment by williamguilhermesouza** [comment]
Solucionado no commit 39703ebd223f8bb1625173c43aaec2610bfe9628 da wiki.

**Comment by LuccasOliveira** [comment]
Inclusão da apresentação Hands-on_at_GIT & GitHub, para treinamento da equipe, e reaberta na issue #4 como enhancement (melhoramento).
